export const eventFormFields = {
  en: {
    page_title: "Create an Event",
    title: "Event Title*",
    description: "Description*",
    description_hint: "Max 500 words",
    event_preview: "Event Preview",
    event_preview_hint: "A short description of the event (max 250 characters)",
    organizer: "Organizer*",
    starts_at: "Start Date and Time*",
    ends_at: "End Date and Time*",
    organizer_hint: "The organizer or host of the event",
    contact: "Contact*",
    contact_hint: "Provide a contact email or social media account",
    instructions: "Instructions",
    instructions_hint: "Sign up instructions or information for the audience",
    tags: "Tags",
    links: "Links",
    links_hint: "Add up to three links relevant to your event",
    link: "Link Text",
    url: "URL",
    main_image: "Main Image",
    additional_images: "Additional Images",
    price: "Price",
    location: "Location",
    address: "Street Address*",
    venue: "Venue Name",
    submit: "Submit Event",
    explore_profiles: "Explore Profiles",
    all: "All",
    full_profile: "Full Profile",
    postal_code: "Postal Code",
  },
  fr: {
    page_title: "Create an Event",
    title: "Event Title*",
    description: "Description*",
    description_hint: "Max 500 words",
    organizer: "Organizer*",
    organizer_hint: "The organizer or host of the event",
    starts_at: "Start Date and Time*",
    ends_at: "End Date and Time*",
    contact: "Contact*",
    contact_hint: "Provide a contact email or social media account",
    instructions: "Instructions",
    instructions_hint: "Sign up instructions or information for the audience",
    tags: "Tags",
    links: "Links",
    links_hint: "Add up to three links relevant to your event",
    link: "Link Text",
    url: "URL",
    main_image: "Main Image",
    additional_images: "Additional Images",
    price: "Price",
    location: "Location",
    address: "Street Address*",
    venue: "Venue Name",
    submit: "Submit Event",
    explore_profiles: "Explore Profiles",
    all: "All",
    full_profile: "Full Profile",
    event_preview: "Event preview",
    event_preview_hint: "A short description of the event (max 250 characters)"
  }
}



export const tags = [
  "Musique",
  "Média",
  "Littéraire",
  "Expérimental",
  "Performance",
  "Visuel",
  "Interdisciplinaire",
  "Autre",
]