export const profileFormFields = {
  en: {
    title: "Create your profile",
    email: "Email address",
    email_hint:"Your email address will not be shown publicly.",
    public_name: "Public Name*",
    public_name_hint: "How would you like to be known publicly?",
    pronouns: "Pronouns",
    pronouns_hint: "What are your preferred pronouns?",
    current_project: "Current project*",
    current_project_hint: "What are you working on now? (500 words)",
    artistic_practice: "Artist Bio*",
    artistic_practice_hint: "Describe your artistic practice (500 words)",
    inspirations: "Inspirations",
    inspirations_hint: "What has inspired you? (500 words)",
    past_projects: "Past Projects",
    past_projects_hint: "Tell us about your past projects (500 words)",
    profile_preview: "Profile preview*",
    profile_preview_hint: "Write a short intro that will appear on your profile preview card (500 characters)",
    tags: "Tags",
    links: "Links",
    links_hint: "Add up to three links to your website, portfolio, or other socials.",
    link: "Link",
    url: "URL",
    photo: "Profile photo",
    submit: "Submit profiles",
  },
  fr: {
    title: "Création du profil",
    email: "Courriel",
    email_hint:"Votre courriel ne sera pas affiché publiquement.",
    public_name: "Nom public*",
    public_name_hint: "Quel nom souhaitez-vous utiliser publiquement?",
    pronouns: "Pronoms",
    pronouns_hint: "Quels sont vos pronoms?",
    current_project: "Projet actuel*",
    current_project_hint: "Sur quoi travaillez-vous présentement? (500 mots)",
    artistic_practice: "Biographie de l’artiste*",
    artistic_practice_hint: "Décrivez votre pratique artistique. (500 mots)",
    inspirations: "Inspirations",
    inspirations_hint: "Qu’est-ce qui vous inspire? (500 mots)",
    past_projects: "Projets antérieurs",
    past_projects_hint: "Parlez-nous de vos projets antérieurs. (500 mots)",
    profile_preview: "Aperçu du profil*",
    profile_preview_hint: "Rédigez une courte introduction qui apparaîtra dans l’aperçu de votre profil. (500 caractères)",
    tags: "Étiquettes",
    links: "Liens",
    links_hint: "Ajoutez jusqu’à trois liens vers votre site Web, votre portfolio ou d’autres réseaux sociaux.",
    link: "lien",
    url: "URL",
    photo: "Photo de profil",
    submit: "Envoyer",
  }
}



export const tags = [
  "Musique",
  "Média",
  "Littéraire",
  "Expérimental",
  "Performance",
  "Visuel",
  "Interdisciplinaire",
  "Autre",
]