export const profileFormFields = {
  en: {
    title: "Create your profile",
    email: "Email Address",
    email_hint:"Your email address will not be shown publicly.",
    public_name: "Public Name*",
    public_name_hint: "How would you like to be known publicly?",
    pronouns: "Pronouns",
    pronouns_hint: "What are your preferred pronouns?",
    current_project: "Current Project*",
    current_project_hint: "What are you working on now? (500 words)",
    artistic_practice: "Artist Bio*",
    artistic_practice_hint: "Describe your artistic practice (500 words)",
    inspirations: "Inspirations",
    inspirations_hint: "What has inspired you? (500 words)",
    past_projects: "Past Projects",
    past_projects_hint: "Tell us about your past projects (500 words)",
    profile_preview: "Profile Preview*",
    profile_preview_hint: "Write a short intro that will appear on your profile preview card (500 characters)",
    tags: "Tags",
    links: "Links",
    links_hint: "Add up to three links to your website, portfolio, or other socials.",
    link: "Link Text",
    url: "URL",
    profile_picture: "Profile Photo",
    location: "What is your location?",
    location_hint: "Your location particulars will be kept private and only used to calculate proximity to help others discover your profile and event. Please read our privacy policy for additional details. If you are more comfortable sharing your postal code, you may do that instead.",
    submit: "Submit Profile",
    explore_profiles: "Explore Profiles",
    all: "All",
    full_profile: "Full Profile",
    postal_code: "Postal Code",
  },
  fr: {
    title: "Création du profil",
    email: "Courriel",
    email_hint:"Votre courriel ne sera pas affiché publiquement.",
    public_name: "Nom Public*",
    public_name_hint: "Quel nom souhaitez-vous utiliser publiquement?",
    pronouns: "Pronoms",
    pronouns_hint: "Quels sont vos pronoms?",
    current_project: "Projet Actuel*",
    current_project_hint: "Sur quoi travaillez-vous présentement? (500 mots)",
    artistic_practice: "Biographie de l’Artiste*",
    artistic_practice_hint: "Décrivez votre pratique artistique. (500 mots)",
    inspirations: "Inspirations",
    inspirations_hint: "Qu’est-ce qui vous inspire? (500 mots)",
    past_projects: "Projets Antérieurs",
    past_projects_hint: "Parlez-nous de vos projets antérieurs. (500 mots)",
    profile_preview: "Aperçu du Profil*",
    profile_preview_hint: "Rédigez une courte introduction qui apparaîtra dans l’aperçu de votre profil. (500 caractères)",
    tags: "Étiquettes",
    links: "Liens",
    links_hint: "Ajoutez jusqu’à trois liens vers votre site Web, votre portfolio ou d’autres réseaux sociaux.",
    link: "lien",
    url: "URL",
    profile_picture: "Photo de Profil",
    location: "What is your location?",
    location_hint: "Your location particulars will be kept private and only used to calculate proximity to help others discover your profile and event. Please read our privacy policy for additional details. If you are more comfortable sharing your postal code, you may do that instead.",
    submit: "Envoyer",
    explore_profiles: "Explorer les Profils",
    all: "Tous",
    full_profile: "Profil Complet",
    postal_code: "Code Postal",
  }
}



export const tags = [
  "Musique",
  "Média",
  "Littéraire",
  "Expérimental",
  "Performance",
  "Visuel",
  "Interdisciplinaire",
  "Autre",
]